library(systemfonts)
library(flexdashboard)
library(shiny)
library(shinydashboard)
library(rsconnect)
library(shinydashboardPlus)
library(DT)
library(plotly)
library(ggplot2)
library(dplyr)
library(corrplot)
library(VIM)
library(leaflet)
library(shinycssloaders)
library(downloadthis)
library(rmarkdown)
library(knitr)
library(nortest)
library(car)
library(broom)
library(gridExtra)
library(viridis)
library(sf)
library(here)
library(mapview)
library(shinyWidgets)
library(writexl)
library(knitr)
library(webshot2)
library(flextable)

data_sovi <- read.csv("data/sovi_data.csv")
names(data_sovi)
data_sovi$DISTRICTCODE <- as.character(data_sovi$DISTRICTCODE)
data_area <- st_read("data/wilayahAdministratif.geojson")
data_matrixDistance <- read.csv("data/matrixDistance.csv")
data_main <- data_sovi